import { createFileRoute, Link } from '@tanstack/react-router'

export const Route = createFileRoute('/terms')({
  head: () => ({ meta: [{ title: 'Terms of Service – ReplyAI' }] }),
  component: TermsPage,
})

function TermsPage() {
  return (
    <main className="min-h-screen bg-white px-4 py-12">
      <div className="max-w-2xl mx-auto">
        <Link to="/" className="text-sm text-gray-400 hover:text-gray-600 transition mb-8 inline-block">← Back to ReplyAI</Link>

        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: May 2025</p>

        <div className="prose prose-gray max-w-none space-y-8 text-gray-700 text-base leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using ReplyAI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">2. Description of Service</h2>
            <p>ReplyAI is a tool that generates suggested reply drafts for customer reviews using artificial intelligence. The Service is provided as a convenience to help small business owners respond to reviews more efficiently.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">3. Use of AI-Generated Content</h2>
            <p>All replies generated by ReplyAI are suggestions only. You are solely responsible for reviewing, editing, and approving any content before publishing it publicly. ReplyAI does not guarantee the accuracy, appropriateness, or fitness of any generated reply for your specific situation.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-gray-600">
              <li>Use the Service for any unlawful purpose</li>
              <li>Submit content that is defamatory, harassing, or fraudulent</li>
              <li>Attempt to circumvent rate limits or abuse the Service</li>
              <li>Use automated scripts or bots to generate replies at scale</li>
              <li>Misrepresent the source of generated content to third parties</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">5. Intellectual Property</h2>
            <p>The text generated by ReplyAI is provided for your personal business use. You retain responsibility for how you use and publish the generated content. ReplyAI claims no ownership over the reply drafts generated on your behalf.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">6. Disclaimer of Warranties</h2>
            <p>The Service is provided "as is" without warranties of any kind, express or implied. ReplyAI does not warrant that the Service will be uninterrupted, error-free, or that generated content will be suitable for your particular use case.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">7. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, ReplyAI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to loss of business, reputation damage, or any other commercial losses.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">8. Third-Party AI Providers</h2>
            <p>ReplyAI uses third-party AI providers (including Groq, Google Gemini, Anthropic, and OpenAI) to generate content. Your use of the Service is also subject to the terms of these providers. ReplyAI is not responsible for the availability or output quality of these third-party services.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">9. Changes to Terms</h2>
            <p>We reserve the right to update these Terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">10. Contact</h2>
            <p>If you have questions about these Terms, please reach out via the contact information available on the site.</p>
          </section>

        </div>

        <div className="mt-12 pt-6 border-t border-gray-100 flex gap-4 text-sm text-gray-400">
          <Link to="/privacy" className="hover:text-gray-600 transition">Privacy Policy</Link>
          <Link to="/" className="hover:text-gray-600 transition">← Back to app</Link>
        </div>
      </div>
    </main>
  )
}
